### ISSUE TITLE
Authentication still working?

### ISSUE THREAD

**Issue by arnolde** [elyby/mojang-api#3]
Hi, I am trying to authenticate like in the "authenticate" method (but actually sending json via Postman).
I followed the instructions on https://wiki.vg/Authentication and in your code, but I keep getting 400 Bad Request.

I am sending this json via POST to https://authserver.mojang.com/authenticate:
{
    "agent": {
        "name": "Minecraft",
        "version": 1
    },
    "username": "myusername",
    "password": "mypassword",
    "requestUser": true
}

Can someone please confirm that this, in general, should be working? Before I bang my head anymore, only to find out the authentication method has changed ;-)

Thanks a lot!

**Comment by turikhay** [comment]
All endpoints are still in use and API haven't changed.
The server responds `400` if the request json is invalid. You may want to check the response body for the exact error message.

**Comment by arnolde** [comment]
EDIT: I got it working now, I still don't know what exactly was wrong, but instead of re-using an old Postman request, I started again from scratch and it worked right away. I guess there was some hidden junk somewhere in the previous collection. Sorry for bothering :-)


OLD:
Thank you! Here is an extract of the response:

```<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>400 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```

Nothing more of any help...

**Comment by turikhay** [comment]
No problem!
I'm glad the issue is now resolved
